function generateSiteMap() {
  return `<?xml version="1.0" encoding="UTF-8"?>

  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
  
    <url>
         <loc>https://www.endy.com/</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>1.0000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/reviews/endy-mattress</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/mattress-design</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/endy-mattress</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/duvet</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/organic-cotton-sheets-sateen</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/collection</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/customizable-pillow</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/solid-wood-bed</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/mattress-protector</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/showrooms</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.8000</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/endy-hybrid-mattress</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/dual-comfort-mattress-topper</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/rv-mattress</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/memory-foam-pillow</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/upholstered-bed</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/platform-bed-frame</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/foam-headboard</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/pillowcases-sateen</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/duvet-cover-sateen</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/weighted-blanket</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/merino-wool-throw-blanket</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/hand-loomed-jute-rug</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/products/grey-geometric-rug</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/reviews/matelas-endy</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/design-du-matelas</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/matelas-endy</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/couette</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/draps-en-coton-biologique-armure-satin</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/collection</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/oreiller-personnalisable</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/lit-en-bois-massif</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/protege-matelas</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/salles-dexposition</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.6400</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/matelas-hybride-endy</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/surmatelas-double-confort</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/matelas-vr</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/oreiller-en-mousse-memoire</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/lit-rembourre</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/base-de-lit-plateforme</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/tete-de-lit-en-mousse</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/taies-d-oreiller-armure-satin</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/housse-de-couette-armure-satin</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/couverture-lestee</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/jete-en-laine-merinos</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/tapis-de-jute-tisse-a-la-main</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
    <url>
         <loc>https://www.endy.com/fr/products/tapis-geometrique-gris</loc>
         <lastmod>2023-03-07T19:15:20+00:00</lastmod>
         <changefreq>daily</changefreq>
         <priority>0.5120</priority>
    </url>
  </urlset>
 `
}

function SiteMap() {
  // getServerSideProps will do the heavy lifting
}

export async function getServerSideProps({ res }) {
  // We generate the XML sitemap with the posts data
  const sitemap = generateSiteMap()

  res.setHeader('Content-Type', 'text/xml')
  // we send the XML to the browser
  res.write(sitemap)
  res.end()

  return {
    props: {}
  }
}

export default SiteMap
